Repository eurec4a/eurec4a-intake, pull requests merged in 2021-02, with the labels that each got.

#40 BAHAMAS: 2020 has been removed from source path
  HALO/BAHAMAS_QL.yaml
Labels: source change

#42 update SMART urls to latest version of files
  HALO/smart_irradiances.yaml
Labels: version update

#47 Velox and KT19 updated the version and deleted source files
  HALO/kt19_cloudmask.yaml
  HALO/velox_cloudmask.yaml
Labels: source vanished, version update

#48 update WALES cloud parameter file to V1.1
  HALO/wales/wales_cloudtop.yaml
Labels: version update

#49 update HALO unified v0.7 -> v0.9
  HALO/bahamas_unified.yaml
  HALO/dropsondes_unified.yaml
  HALO/radar_unified.yaml
  HALO/radiometer_unified.yaml
Labels: version update
